# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-11 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('application', models.FileField(upload_to='./applications/')),
                ('resume', models.FileField(upload_to='./resume/')),
                ('transcript_or_certificate', models.FileField(upload_to='./college_transcript_or_certificate/', verbose_name='Official College Transcripts, if not then High School Transcripts/Diploma/GED')),
                ('certificate_or_license_for_position', models.FileField(blank=True, upload_to='./certificate_or_license_for_position', verbose_name='Certificate or License applicable to the position (if applicable)')),
                ('letter_of_interest', models.FileField(upload_to='./letter_of_interest/', verbose_name='Letter of Interest for the position')),
                ('first_letter_of_recommendation', models.FileField(upload_to='./first_letter_of_recommendation/')),
                ('second_letter_of_recommendation', models.FileField(upload_to='./second_letter_of_recommendation/')),
                ('third_letter_of_recommendation', models.FileField(upload_to='./third_letter_of_recommendation/')),
                ('personal_growth', models.FileField(blank=True, upload_to='./personal_growth/', verbose_name='Personal Growth (Teachers Only)')),
                ('certificate_of_completion', models.FileField(blank=True, upload_to='./certificate_of_completion', verbose_name='Certificate of Completion - 16 hours Employable Skills Training (if no college degree)')),
                ('apply_date', models.DateField(verbose_name='apply date')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(default='')),
                ('job_overview', models.TextField(default='')),
                ('qualifications', models.TextField(default='')),
                ('job_pd', models.FileField(blank=True, upload_to='./job_pd')),
                ('post_date', models.DateField(verbose_name='post date')),
                ('due_date', models.DateField(verbose_name='due date')),
            ],
        ),
    ]
