# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-11 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='job_pd',
            new_name='job_PD',
        ),
    ]
