# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-13 15:04
from __future__ import unicode_literals

import Employment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employment', '0002_auto_20170711_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='certificate_of_completion',
            field=models.FileField(blank=True, upload_to='./certificate_of_completion', validators=[Employment.validators.validate_file_extension], verbose_name='Certificate of Completion - 16 hours Employable Skills Training (if no college degree)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='certificate_or_license_for_position',
            field=models.FileField(blank=True, upload_to='./certificate_or_license_for_position', validators=[Employment.validators.validate_file_extension], verbose_name='Certificate or License applicable to the position (if applicable)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_letter_of_recommendation',
            field=models.FileField(blank=True, upload_to='./first_letter_of_recommendation/', validators=[Employment.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='application',
            name='letter_of_interest',
            field=models.FileField(blank=True, upload_to='./letter_of_interest/', validators=[Employment.validators.validate_file_extension], verbose_name='Letter of Interest for the position'),
        ),
        migrations.AlterField(
            model_name='application',
            name='personal_growth',
            field=models.FileField(blank=True, upload_to='./personal_growth/', validators=[Employment.validators.validate_file_extension], verbose_name='Personal Growth (Teachers Only)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='second_letter_of_recommendation',
            field=models.FileField(blank=True, upload_to='./second_letter_of_recommendation/', validators=[Employment.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='application',
            name='third_letter_of_recommendation',
            field=models.FileField(blank=True, upload_to='./third_letter_of_recommendation/', validators=[Employment.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='application',
            name='transcript_or_certificate',
            field=models.FileField(blank=True, upload_to='./college_transcript_or_certificate/', validators=[Employment.validators.validate_file_extension], verbose_name='Official College Transcripts, if not then High School Transcripts/Diploma/GED'),
        ),
    ]
