# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-13 16:43
from __future__ import unicode_literals

import Employment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employment', '0003_auto_20170713_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application',
            field=models.FileField(upload_to='./applications/', validators=[Employment.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='./resume/', validators=[Employment.validators.validate_file_extension]),
        ),
    ]
