# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-14 20:35
from __future__ import unicode_literals

import Employment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employment', '0004_auto_20170713_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='certificate_of_indian_blood',
            field=models.FileField(blank=True, upload_to='./certificate_of_indian_blood/', validators=[Employment.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_title',
            field=models.CharField(max_length=300),
        ),
    ]
