# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-18 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employment', '0005_auto_20170714_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='./attachments/')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employment.Application')),
            ],
        ),
    ]
