# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-18 14:21
from __future__ import unicode_literals

import Employment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employment', '0006_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application',
        ),
        migrations.RemoveField(
            model_name='application',
            name='certificate_of_completion',
        ),
        migrations.RemoveField(
            model_name='application',
            name='certificate_of_indian_blood',
        ),
        migrations.RemoveField(
            model_name='application',
            name='certificate_or_license_for_position',
        ),
        migrations.RemoveField(
            model_name='application',
            name='first_letter_of_recommendation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='letter_of_interest',
        ),
        migrations.RemoveField(
            model_name='application',
            name='personal_growth',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='application',
            name='second_letter_of_recommendation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='third_letter_of_recommendation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='transcript_or_certificate',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='./attachments/', validators=[Employment.validators.validate_file_extension]),
        ),
    ]
