# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-18 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employment', '0008_guideline'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideline',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
